network:
  version: 2
  renderer: networkd
  ethernets:
     vlan_desk:
      match: {macaddress: "08:00:88:ac:11:11"}
      set-name: vlan_desk
      dhcp4: false
      addresses: [ "172.28.100.10/24" ]
      routes:
        - to: default
          via: 172.28.100.254
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]

