network:
  version: 2
  renderer: networkd
  ethernets:
    vlan_dmz:
      match:
        macaddress: "08:00:27:bd:11:10"
      set-name: vlan_dmz
      dhcp4: false
      addresses: [ "172.28.200.10/24" ]
      routes:
        - to: default
          via: 172.28.200.254
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]



